name: collBM
version: 0.0.1
authors:
  - Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/tejainece/collBM
description: A simple performance analysis of different collections in Dart
dependencies:
  quiver: "^0.22.0"
